# Generated by Django 2.2.3 on 2020-12-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportes', '0014_auto_20201202_1813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial de reserva')),
                ('fecha_final', models.DateField(verbose_name='Fecha inicial de reserva')),
                ('cantidad_dias', models.SmallIntegerField(default=7, verbose_name='Cantidad de dias a reservar')),
                ('created', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.Deporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
