# Generated by Django 2.2.3 on 2020-12-23 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0014_auto_20201202_1813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0002_auto_20201217_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='ReservaDeporte',
        ),
    ]
