# Generated by Django 2.2.3 on 2020-12-23 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0014_auto_20201202_1813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0004_auto_20201223_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva_Deporte',
            new_name='ReservaDeporte',
        ),
    ]
