# Generated by Django 2.2.3 on 2020-12-23 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_auto_20201222_0923'),
        ('hoteles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turismos', '0001_initial'),
        ('reservas', '0005_auto_20201223_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservadeporte',
            options={'verbose_name': 'la reserva', 'verbose_name_plural': 'Deportes reservados'},
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.Deporte', verbose_name='Deporte reservado'),
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reservado por'),
        ),
        migrations.CreateModel(
            name='ReservaTurismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial de reserva')),
                ('fecha_final', models.DateField(verbose_name='Fecha final de reserva')),
                ('cantidad_dias', models.SmallIntegerField(default=7, verbose_name='Cantidad de dias a reservar')),
                ('created', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('turismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismos.Turismo', verbose_name='Lugar Turistico reservado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reservado por')),
            ],
            options={
                'verbose_name': 'la reserva',
                'verbose_name_plural': 'Lugare turisticos reservados reservados',
            },
        ),
        migrations.CreateModel(
            name='ReservaPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial de reserva')),
                ('fecha_final', models.DateField(verbose_name='Fecha final de reserva')),
                ('cantidad_dias', models.SmallIntegerField(default=7, verbose_name='Cantidad de dias a reservar')),
                ('created', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.Plato', verbose_name='Plato Tipico reservado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reservado por')),
            ],
            options={
                'verbose_name': 'la reserva',
                'verbose_name_plural': 'Platos Tipicos reservados',
            },
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial de reserva')),
                ('fecha_final', models.DateField(verbose_name='Fecha final de reserva')),
                ('cantidad_dias', models.SmallIntegerField(default=7, verbose_name='Cantidad de dias a reservar')),
                ('created', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel', verbose_name='Cabaña reservado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reservado por')),
            ],
            options={
                'verbose_name': 'la reserva',
                'verbose_name_plural': 'Cabañas reservados',
            },
        ),
    ]
