# Generated by Django 2.2.3 on 2020-12-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20201223_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaturismo',
            options={'verbose_name': 'la reserva', 'verbose_name_plural': 'Lugares turisticos reservados'},
        ),
        migrations.AddField(
            model_name='reservadeporte',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='reservahotel',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='reservaplato',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='reservaturismo',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='reservaplato',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='reservaturismo',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion'),
        ),
    ]
