# Generated by Django 2.2.3 on 2021-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_auto_20201224_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadeporte',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='reservadeporte',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modificado'),
        ),
    ]
