# Generated by Django 2.2.3 on 2020-11-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='estado',
        ),
        migrations.AddField(
            model_name='deporte',
            name='cantidad',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes/deportes/', verbose_name='Imagen'),
        ),
    ]
