# Generated by Django 2.2.3 on 2020-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0003_auto_20201127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='deportes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion'),
        ),
    ]
