# Generated by Django 2.2.3 on 2020-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0009_deporte_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='descripcion2',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion2'),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
