# Generated by Django 2.2.3 on 2020-12-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0010_auto_20201202_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='created',
        ),
        migrations.RemoveField(
            model_name='deporte',
            name='modified',
        ),
    ]
