# Generated by Django 2.2.3 on 2020-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0011_auto_20201202_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='descripcion2',
        ),
        migrations.AddField(
            model_name='deporte',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion'),
        ),
    ]
