# Generated by Django 2.2.3 on 2020-12-02 22:22

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0012_auto_20201202_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='imagen_prueba',
            field=smartfields.fields.ImageField(blank=True, max_length=200, null=True, upload_to='imagenes/prueba/', verbose_name='Imagen de prueba'),
        ),
    ]
