# Generated by Django 2.2.3 on 2020-12-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['nombre'], 'verbose_name': 'Plato', 'verbose_name_plural': 'Platos Tipicos'},
        ),
    ]
