# Generated by Django 2.2.3 on 2020-12-06 18:21

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201124_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_usuario',
            field=smartfields.fields.ImageField(blank=True, max_length=200, null=True, upload_to='imagenes/usuarios/%Y/%m/%d/', verbose_name='Imagen'),
        ),
    ]
