# Generated by Django 2.2.3 on 2020-12-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201206_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen_usuario',
            new_name='imagen',
        ),
    ]
