# Generated by Django 2.2.3 on 2021-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20201206_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ultima modificación'),
        ),
    ]
