# Generated by Django 2.2.3 on 2020-12-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('cantidad', models.SmallIntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('imagen', smartfields.fields.ImageField(blank=True, max_length=200, null=True, upload_to='imagenes/cabañas/%Y/%m/%d/', verbose_name='Imagen')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de publicacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificacion')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Cabañas',
                'ordering': ['nombre'],
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
